### PR TITLE
Struct for converting some member functions to static

### PR DESCRIPTION
**Pull request by kstppd**
@ursg  @ikotipal This is what I propose for issue #17 , I am not sure I should have made a PR here because this was Leo's idea so if you all agree I guess Leo can implement these and then I can go ahead with the rest

### CODE REVIEW

**Comment by kstppd** [comment]
Seems I cannot tag Leo here...

**Comment by kstppd** [comment]
However this does not break backwards compatibility so if we go this route we only need to delete the copyp-pasted functions in vlsvdiff et.al

**Comment by lkotipal** [comment]
Yeah, this looks like a better solution than what I got. Merging your PR is fine by me as well.

**Comment by ursg** [comment]
Hmm, nice! I like this solution, because it allows for accessibility of these methods through both the FsgridTools object and their concrete implementations.

Now the only release engineering question here is: do we merge this into the fsgrid master branch right away, update vlasiator's dev branch and require the updated version from there on out?
We might even tag a fsgrid release before the merge, so that the current vlasiator master can simply continue to run fine with that version.

For Vlasiator's next master release (v5.2) we can then let everybody know that they'll need this updated version in the release notes.

Opinions?

**Comment by ykempf** [comment]
> Opinions?

I'll follow the lead (developer).

Could you have the old-interface functions still existing and throwing a "this is deprecated, please update" message?

**Comment by ursg** [comment]
Not a bad idea actually. Then we could merge this, leave the deprecation warning in until the next proper release, and then toss them out.

**Comment by kstppd** [comment]
I am not sure I understand where to add the warning message?

**Comment by ykempf** [comment]
Hmm most likely one will have a newer vlasiator using an outdated fsgrid. So maybe it's not that easy. Can we develop the script stuff around version.cpp to check the git hash of libraries and warn if it's not the "recommended" version?

**Comment by kstppd** [comment]
I 'll have a look. I get your point.

**Comment by ykempf** [comment]
But this then goes beyond this issue, we could have a tool checking versions of other libraries, especially dccrg, fsgrid, vlsv, phiprof, the homegrowm ones.

**Comment by kstppd** [comment]
True and that could actually be useful for production as well

**Comment by ykempf** [comment]
As opposed to all the not-actually-useful stuff we do all the time. ;) :D

**Comment by kstppd** [comment]
Nahh you know what I mean :)

**Comment by iljah** [comment]
#error or #warning might work if entire function is not supposed to be 
used anymore: https://gcc.gnu.org/onlinedocs/cpp/Diagnostics.html

**Comment by ursg** [comment]
I'm not that worried about "New vlasiator using the outdated fsgrid" case. It either works, or it fails on compile time and then the user curses and updates fsgrid. So that's fine from my point of view.
Do the calls to targetGrid.calcLocalSize in ioread.cpp actually continue to work as before with this change, even though the functions are static and inherited?

**Comment by kstppd** [comment]
Yep since they are inherited they will work when called using the object member and when called by someone as FsGridTools::calcLocalStart(...)

**Comment by kstppd** [comment]
I did compile yesterday but I can re-verify but in a bit as I am in a nice git wreck at the moment

**Comment by ursg** [comment]
I just tested this, and indeed, it compiles just fine. So in that case, all is good to merge IMHO!

**Comment by kstppd** [comment]
Yep I just did as well passes the restart read and write tests in testpackage

**Comment by kstppd** [comment]
So we just need to take care of the places we have copied and pasted those tool functions. Instead we just include fsgrid.

**Pull request merged**
